00:28:21 [501][6]: Exception in /home/corey/git/bap/logger/log:9
00:28:21 [501][6]: Stack trace:
00:28:21 [501][6]: #0 {main}
00:30:08 [514][6]: Exception[msg[] line[9] file[/home/corey/git/bap/logger/log] trace[#0 {main}]]
00:30:59 [518][6]: Exception[/home/corey/git/bap/logger/log@9:  trace[#0 {main}]]
00:32:36 [531][6]: {closure}(): Exception[/home/corey/git/bap/logger/log@11:  trace[#0 /home/corey/git/bap/logger/log(12): {closure}()
00:32:36 [531][6]: {closure}(): #1 {main}]]
00:33:33 [535][6]: {closure}(): Exception[/home/corey/git/bap/logger/log@11: 
00:33:33 [535][6]: {closure}(): #0 /home/corey/git/bap/logger/log(12): {closure}()
00:33:33 [535][6]: {closure}(): #1 {main}]
00:33:44 [539][6]: {closure}(): Exception in /home/corey/git/bap/logger/log@11: 
00:33:44 [539][6]: {closure}(): #0 /home/corey/git/bap/logger/log(12): {closure}()
00:33:44 [539][6]: {closure}(): #1 {main}
00:37:52 [547][6]: {closure}(): Exception in /home/corey/git/bap/logger/log@11: 
00:37:52 [547][6]: {closure}(): #0 /home/corey/git/bap/logger/log(12): {closure}()
00:37:52 [547][6]: {closure}(): #1 {main}
00:42:14 [551][6]: {closure}(): Exception in /home/corey/git/bap/logger/log(11): 
00:42:14 [551][6]: {closure}(): #0 /home/corey/git/bap/logger/log(12): {closure}()
00:42:14 [551][6]: {closure}(): #1 {main}
00:45:18 [559][6]: {closure}(): Exception in /home/corey/git/bap/logger/log(11): 
00:45:18 [559][6]: {closure}(): #0 /home/corey/git/bap/logger/log(12): {closure}()
00:45:18 [559][6]: {closure}(): #1 {main}
13:23:51 [788][6]: {closure}(): Exception in /home/corey/git/bap/logger/log(11): 
13:23:51 [788][6]: {closure}(): #0 /home/corey/git/bap/logger/log(12): {closure}()
13:23:51 [788][6]: {closure}(): #1 {main}
14:50:37 [796][6]: {closure}(): Exception in /home/corey/git/bap/logger/log(12): 
14:50:37 [796][6]: {closure}(): #0 /home/corey/git/bap/logger/log(13): {closure}()
14:50:37 [796][6]: {closure}(): #1 {main}
